### ISSUE TITLE
ERROR: Got sbt.ResolveException while running compile.

### ISSUE THREAD

**Issue by ghost** [dhgarrette/low-resource-pos-tagging-2014#1]
I called $ ./compile in a linux terminal while in /low-resource-pos-tagging-2014.
ERROR MESSAGE:

[warn]  module not found: com.typesafe.sbt#sbt-start-script;0.10.0
        [warn] ==== typesafe-ivy-releases: tried
        [warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-start-script/scala_2.10/sbt_0.13/0.10.0/ivys/ivy.xml
        [warn] ==== sbt-plugin-releases: tried
        [warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-start-script/scala_2.10/sbt_0.13/0.10.0/ivys/ivy.xml
        [warn] ==== local: tried
        [warn]   /home/rheadedhia/.ivy2/local/com.typesafe.sbt/sbt-start-script/scala_2.10/sbt_0.13/0.10.0/ivys/ivy.xml
        [warn] ==== public: tried
        [warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-start-script_2.10_0.13/0.10.0/sbt-start-script-0.10.0.pom
        [info] Resolving org.fusesource.jansi#jansi;1.4 ...
        [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
        [warn]  ::          UNRESOLVED DEPENDENCIES         ::
        [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
        [warn]  :: com.typesafe.sbt#sbt-start-script;0.10.0: not found
        [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
        [warn] 
        [warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
        [warn]      com.typesafe.sbt:sbt-start-script:0.10.0 (sbtVersion=0.13, scalaVersion=2.10)
        [warn] 
        [warn]  Note: Unresolved dependencies path:
        [warn]      com.typesafe.sbt:sbt-start-script:0.10.0 (sbtVersion=0.13, scalaVersion=2.10) (/home/rheadedhia/Documents/low-resource-pos-tagging-2014-master/project/plugins.sbt#L1-2)
        [warn]        +- default:low-resource-pos-tagging-2014-master-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
        sbt.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-start-script;0.10.0: not found
            at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
            at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
            at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
            at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
            at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
            at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
            at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
            at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
            at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
            at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
            at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
            at xsbt.boot.Using$.withResource(Using.scala:10)
            at xsbt.boot.Using$.apply(Using.scala:9)
            at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
            at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
            at xsbt.boot.Locks$.apply0(Locks.scala:31)
            at xsbt.boot.Locks$.apply(Locks.scala:28)
            at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
            at sbt.IvySbt.withIvy(Ivy.scala:119)
            at sbt.IvySbt.withIvy(Ivy.scala:116)
            at sbt.IvySbt$Module.withModule(Ivy.scala:147)
            at sbt.IvyActions$.updateEither(IvyActions.scala:156)
            at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1282)
            at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1279)
            at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1309)
            at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1307)
            at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
            at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1312)
            at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1306)
            at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
            at sbt.Classpaths$.cachedUpdate(Defaults.scala:1324)
            at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1264)
            at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1242)
            at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
            at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
            at sbt.std.Transform$$anon$4.work(System.scala:63)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
            at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
            at sbt.Execute.work(Execute.scala:235)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
            at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
        [error](*:update) sbt.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-start-script;0.10.0: not found

Please let me know if you need any more information.
Thanks!

**Comment by dhgarrette** [comment]
Are you connected to the internet?  It's saying it can't find `https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-start-script/scala_2.10/sbt_0.13/0.10.0/ivys/ivy.xml`, but that file does exist on the web.

**Comment by ghost** [comment]
It worked now, I guess the internet must have been down. Thanks!
